# Generated by Django 6.0.5 on 2026-06-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='Geografik kenglik (Latitude)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='Geografik uzunlik (Longitude)'),
            preserve_default=False,
        ),
    ]
