# Generated by Django 6.0.5 on 2026-06-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_venue_latitude_alter_venue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Geografik kenglik (Latitude)'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Geografik uzunlik (Longitude)'),
        ),
    ]
