# Generated by Django 6.0.5 on 2026-08-22 05:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_alter_venue_latitude_alter_venue_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_type',
            field=models.CharField(choices=[('deposit_50', "50% Avans To'lov"), ('full_100', "100% To'liq To'lov")], default='deposit_50', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_holder', models.CharField(max_length=100, verbose_name='Karta egasi')),
                ('card_masked', models.CharField(max_length=19, verbose_name='Masklangan Karta (8600 **** **** 1234)')),
                ('card_token', models.CharField(max_length=255, unique=True, verbose_name='Token')),
                ('expire_month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('expire_year', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(24), django.core.validators.MaxValueValidator(45)])),
                ('provider', models.CharField(choices=[('click', '💳 Click'), ('payme', '📱 Payme')], default='click', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foydalanuvchi Kartasi',
                'verbose_name_plural': 'Foydalanuvchilar Kartalari',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apps.usercard'),
        ),
    ]
