# Generated by Django 6.0.5 on 2026-08-29 10:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_booking_paid_amount_booking_payment_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="Masalan: 'Yangi yil aksiyasi' yoki 'Bayram narxi'. Faqat admin uchun, foydalanuvchiga ko'rinadi.", max_length=150, verbose_name='Nomi')),
                ('scope', models.CharField(choices=[('all', '🌍 Barcha maydonlar uchun'), ('sport', "⚽ Sport turi bo'yicha"), ('venue', '🏟 Bitta maydon uchun')], default='all', max_length=10, verbose_name='Qamrovi')),
                ('discount_type', models.CharField(choices=[('decrease', '🔻 Chegirma (narxni kamaytirish)'), ('increase', '🔺 Ustama (narxni oshirish)')], default='decrease', max_length=10, verbose_name='Turi')),
                ('percent', models.DecimalField(decimal_places=2, help_text='Masalan: 25.00 yoki 30.00', max_digits=5, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(500)], verbose_name='Foizi (%)')),
                ('start_date', models.DateField(help_text='Chegirma shu sanadan boshlab amal qiladi', verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(help_text='Chegirma shu sanada (kiritilgan kun ham) tugaydi', verbose_name='Tugash sanasi')),
                ('is_active', models.BooleanField(default=True, help_text="O'chirilsa, muddati tugamagan bo'lsa ham qo'llanmaydi", verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('sport', models.ForeignKey(blank=True, help_text="Faqat qamrov 'Sport turi bo'yicha' bo'lsa tanlanadi.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='apps.sporttype', verbose_name='Sport turi')),
                ('venue', models.ForeignKey(blank=True, help_text="Faqat qamrov 'Bitta maydon uchun' bo'lsa tanlanadi.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='apps.venue', verbose_name='Maydon')),
            ],
            options={
                'verbose_name': 'Chegirma',
                'verbose_name_plural': 'Chegirmalar',
                'ordering': ('-created_at',),
            },
        ),
    ]
