services:
  backend_service:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    env_file: backend/.env
    volumes:
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
     - postgres_service

  frontend_service:
    build:
      context: frontend/
      dockerfile: Dockerfile
    env_file: frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend_service

  postgres_service:
    image: postgres:alpine
    environment:
      POSTGRES_DB: play_arena
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_service:
    image: redis:alpine

volumes:
  media:
  pgdata:
